### ISSUE TITLE
Not works with Picasso library

### ISSUE THREAD

**Issue by GAV-516** [justasm/WindowView#3]
Hi!
Is it possible to make this works with [ Picasso](http://square.github.io/picasso) library?
Currently when I trying to do like this:

```
    Picasso.with(this)
            .load(R.drawable.splash)
            .fit()
            .centerCrop()
            .into(ivSplash);
```

I got _NullPointerException_:
E/AndroidRuntime(10358): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.Drawable.getIntrinsicWidth()' on a null object reference
E/AndroidRuntime(10358):    at com.jmedeisis.windowview.WindowView.onSizeChanged(WindowView.java:283)
E/AndroidRuntime(10358):    at android.view.View.sizeChange(View.java:15793)
E/AndroidRuntime(10358):    at android.view.View.setFrame(View.java:15758)
E/AndroidRuntime(10358):    at android.widget.ImageView.setFrame(ImageView.java:1019)
E/AndroidRuntime(10358):    at android.view.View.layout(View.java:15674)
E/AndroidRuntime(10358):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(10358):    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(10358):    at android.view.View.layout(View.java:15678)
E/AndroidRuntime(10358):    at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(10358):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(10358):    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(10358):    at android.view.View.layout(View.java:15678)
E/AndroidRuntime(10358):    at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(10358):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
E/AndroidRuntime(10358):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
E/AndroidRuntime(10358):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
E/AndroidRuntime(10358):    at android.view.View.layout(View.java:15678)
E/AndroidRuntime(10358):    at android.view.ViewGroup.layout(ViewGroup.java:5039)
E/AndroidRuntime(10358):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(10358):    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)

**Comment by justasm** [comment]
Thanks for bringing this to attention!

Loading with Picasso (and/or dynamically changing the image in any other way) should work in the latest 0.1.1 release.

I'd recommend using Picasso as follows:

``` java
Picasso.with(this)
    .load(/* */)
    .into(/* */);
```

i.e. omit the `fit()` and `centerCrop()`, because in that case Picasso crops the image to exactly match the View's dimensions and WindowView cannot reveal more of the image upon device tilt.
